<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('aesGcm')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_aesGcm.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('aesGcm.so')) return;
    } else {
      if (!dl('aesGcm.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class aesGcm {
	static function aesGcmEncrypt($key,$IV,$header,$headerLength,$plaintext,$plaintextLength,$ciphertext,$tag) {
		return aesGcmEncrypt($key,$IV,$header,$headerLength,$plaintext,$plaintextLength,$ciphertext,$tag);
	}

	static function aesGcmDecrypt($key,$IV,$header,$headerLength,$ciphertext,$ciphertextLength,$plaintext,$tag) {
		return aesGcmDecrypt($key,$IV,$header,$headerLength,$ciphertext,$ciphertextLength,$plaintext,$tag);
	}

	static function generateAESKey($AESKEY,$seedValue) {
		generateAESKey($AESKEY,$seedValue);
	}

	static function generateSeedValue($seedValue,$len) {
		return generateSeedValue($seedValue,$len);
	}
}

/* PHP Proxy Classes */

?>
