<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('eccsi')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_eccsi.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('eccsi.so')) return;
    } else {
      if (!dl('eccsi.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class eccsi {
	static function todayECCSI() {
		return todayECCSI();
	}

	static function validateECCSIUserKey($date,$ID,$IDLength,$KPAK,$PVTSSK) {
		return validateECCSIUserKey($date,$ID,$IDLength,$KPAK,$PVTSSK);
	}

	static function createSignature($TPE,$M,$MLength,$ID,$IDLength,$KPAK,$PVTSSK,$TP,$SIGNATURE,$seedValue) {
		return createSignature($TPE,$M,$MLength,$ID,$IDLength,$KPAK,$PVTSSK,$TP,$SIGNATURE,$seedValue);
	}

	static function verifySignature($TPE,$M,$MLength,$ID,$IDLength,$KPAK,$SIGNATURE) {
		return verifySignature($TPE,$M,$MLength,$ID,$IDLength,$KPAK,$SIGNATURE);
	}
}

/* PHP Proxy Classes */

?>
