<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('sakke')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_sakke.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('sakke.so')) return;
    } else {
      if (!dl('sakke.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class sakke {
	static function todaySAKKE() {
		return todaySAKKE();
	}

	static function encapsulateSSV($SSV,$ZS,$TPE,$ID,$IDLength,$HRbS) {
		return encapsulateSSV($SSV,$ZS,$TPE,$ID,$IDLength,$HRbS);
	}

	static function validateRSK($ZS,$ID,$IDLength,$KbS) {
		return validateRSK($ZS,$ID,$IDLength,$KbS);
	}

	static function validateSAKKETimePermit($date,$ID,$IDLength,$ZS,$KbS,$TP) {
		return validateSAKKETimePermit($date,$ID,$IDLength,$ZS,$KbS,$TP);
	}

	static function decapsulateSSV($HRbS,$ZS,$TPE,$ID,$IDLength,$KbS,$TP,$SSV) {
		return decapsulateSSV($HRbS,$ZS,$TPE,$ID,$IDLength,$KbS,$TP,$SSV);
	}
}

/* PHP Proxy Classes */

?>
